name: Artifacts Test

on: workflow_dispatch

jobs:
  repeat-artifacts-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./react-gh-actions/build
          name: custom=name-for-build-files
  repeat-artifacts-deploy:
    needs: repeat-artifacts-build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get Built project
        uses: actions/download-artifact@v3
        with:
          name: custom=name-for-build-files
