name: Print Pull Request Context
on: [workflow_dispatch]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print event of issue
        run: echo "${{ github }}"

      - name: Print event of issue
        run: echo "${{ toJSON(github) }}"

      - name: Print Pull Request Context
        run: echo "${{ toJSON(github.event) }}"
