name: Deploy React App Chained

on: push

jobs:
  test_react_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get Access to repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci # We can use npm install as well. But this is better and more safe.
        # works if we have package-lock.json in our folder. CI mentioned in recommendations
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run lint
      - name: Deploy
        run: echo Deploying...
