name: Deploy React App. Cached dependencies v2

on: push

jobs:
  test_react_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get access to repo
        uses: actions/checkout@v3

      - name: Cache modules
        id: cache-for-testing
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-testing-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-for-testing.outputs.cache-hit != 'true'
        run: npm install

      - name: Test application
        run: npm run test

  # lint_react_app:
  #   runs-on: ubuntu-latest
  #   needs: test_react_app
  #   defaults:
  #     run:
  #       working-directory: ./react-gh-actions
  #   steps:
  #     - name: Get Access to repo
  #       uses: actions/checkout@v3

  #     - name: Restore dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  #     - name: Lint application
  #       run: npm run lint

  build_react_app:
    runs-on: ubuntu-latest
    needs: test_react_app
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get Access to repo
        uses: actions/checkout@v3

      - name: Cached dependencies
        id: cache-for-build
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-for-build.outputs.cache-hit != 'true'
        run: npm install

      - name: Build application
        run: npm run build
