name: Deploy React App. Cached dependencies v5

on: workflow_dispatch

jobs:
  test_react_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get access to repo
        uses: actions/checkout@v3

      - name: Cache modules
        id: cache-for-testing
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-for-testing.outputs.cache-hit != 'true'
        run: npm ci

      - name: Test application
        run: npm run test

  lint_react_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get Access to repo
        uses: actions/checkout@v3

      - name: Cache modules
        id: cache-for-building
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-for-building.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint application
        run: npm run lint

  build_react_app:
    needs: [test_react_app, lint_react_app]
    continue-on-error: true # if build failed on some OS - test will not stop
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16, 18]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get Access to repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ node-version.os }}

      - name: Cache modules
        id: cache-for-building
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-for-building.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build application
        run: npm run build
