name: Deploy React App. Cached dependencies

on: workflow_dispatch

jobs:
  test_react_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get access to repo
        uses: actions/checkout@v3

      - name: Cache modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm run test

  # lint_react_app:
  #   runs-on: ubuntu-latest
  #   needs: test_react_app
  #   defaults:
  #     run:
  #       working-directory: ./react-gh-actions
  #   steps:
  #     - name: Get Access to repo
  #       uses: actions/checkout@v3

  #     - name: Restore dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  #     - name: Lint application
  #       run: npm run lint

  build_react_app:
    runs-on: ubuntu-latest
    needs: test_react_app
    defaults:
      run:
        working-directory: ./react-gh-actions
    steps:
      - name: Get Access to repo
        uses: actions/checkout@v3

      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
