name: Print Pull Request Context

on: workflow_dispatch # Before was a "push" value

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "${{ github }}"
