name: Test React App
on: push
jobs:
  steps:
    - name: Get Access to repo
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci # We can use npm install as well. But this is better and more safe.
      # works if we have package-lock.json in our folder. CI mentioned in recommendations
    - name: Test application
      run: npm run test
